### ISSUE TITLE
Study SER and train 2 models (V/A)

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/readys#21]

**Comment by tyiannak** [comment]
Note: this task should take care of the architectural aspects: we should be able to dynamically add a new speech-related model with N classes and automatically the recording-level-feature-extraction function should extract N more features (classifiers should be put in a config file)

**Comment by sofiaele** [comment]
Report : [https://docs.google.com/document/d/1dXMv6ZWJOH9MYrXKI8vVZEk1LsnH18Ou_X7OjP2AWgc/edit?usp=sharing](url)
