### ISSUE TITLE
Use the recording-level-feature-extraction function to extract features for a simple binary task

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/readys#22]

**Comment by sofiaele** [comment]
Use self-recorded data for a binary classification task (bad/good). Feature extraction by audio and text analysis, save them into a features.csv file , plotting them per feature and train multiple classifiers with gridsearch evaluation (GaussianNB, Knn, Svm, Logistic regression) . Scores: 0.85, 1,  0.9, 0.85

**Comment by sofiaele** [comment]
Report : [https://docs.google.com/document/d/1JAyIaqOVrlB6Aho5f_DFzWhSsh7uFIRFeoUzAYAcLMg/edit?usp=sharing](url)

**Comment by tyiannak** [comment]
ok
