### ISSUE TITLE
Improve training of audio and test segment classifiers (train_text and train_audio)

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/readys#31]

**Comment by tyiannak** [comment]
@lobracost among others please repair the following:

line 140-142 in train_text compute the confusion matrix, but on the training data after the cross validation procedure is over. Please make it part of the cross validation procedure (as with the f1 macro metric).

**Comment by tyiannak** [comment]
add XGBoost in requirements @lobracost

**Comment by sofiaele** [comment]
@lobracost error with Smote initialization when having  very few samples per class : 
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 5, n_neighbors = 6 .
A solution can be found here: [https://stackoverflow.com/questions/49395939/smote-initialisation-expects-n-neighbors-n-samples-but-n-samples-n-neighbo](url). 
We will discuss whether it is worth the change.
