### ISSUE TITLE
Baseline recording level classifier

### ISSUE THREAD

**Issue by lobracost** [tyiannak/readys#38]

**Comment by lobracost** [comment]
Create a baseline_recording_level_classification method that trains a classifier in three different ways:
1. Using audio features only
2. Using text embeddings only
3. Using a fusion of both audio and text features

**Comment by tyiannak** [comment]
for 1 just use pyAudioAnalysis extract_features_and_train function.
for 2 use some simple averaging on glove
for 3 just merge 1 and 2
